"""Small, explicit registries for Pine namespaces and constants.

The interpreter intentionally does not attempt to mirror every TradingView
constant.  Keeping the supported surface in one place makes semantic
diagnostics precise and gives the backtest runtime a conservative fallback for
names that are not modeled yet.
"""

from __future__ import annotations

from types import MappingProxyType
from typing import Any


def _members(*values: str) -> frozenset[str]:
    return frozenset(values)


# Namespaces are deliberately broader than the set of members implemented by
# the runtime.  A member can therefore be recognized as a Pine namespace while
# still receiving an explicit unsupported-feature result when it is evaluated.
_NAMESPACE_MEMBERS: dict[str, frozenset[str]] = {
    "array": _members(
        "new_float",
        "new_int",
        "new_bool",
        "new_string",
        "new_line",
        "from",
        "push",
        "pop",
        "get",
        "set",
        "size",
        "clear",
        "shift",
        "unshift",
        "insert",
        "remove",
        "slice",
        "concat",
        "sort",
        "reverse",
        "includes",
        "indexof",
        "lastindexof",
        "abs",
        "avg",
        "max",
        "min",
        "sum",
        "stdev",
        "variance",
        "median",
        "mode",
        "range",
        "covariance",
        "percentile_linear_interpolation",
        "percentile_nearest_rank",
        "percentrank",
        "join",
        "copy",
        "fill",
        "binary_search",
        "sort_indices",
        "every",
        "some",
    ),
    "barmerge": _members("gaps_on", "gaps_off", "lookahead_on", "lookahead_off"),
    "box": _members(
        "new",
        "delete",
        "set_left",
        "set_right",
        "set_top",
        "set_bottom",
        "set_bgcolor",
        "set_border_color",
        "set_border_width",
        "set_extend",
        "set_text",
        "set_text_color",
        "set_text_size",
        "set_text_halign",
        "set_text_valign",
        "set_lefttop",
        "set_rightbottom",
        "get_left",
        "get_right",
        "get_top",
        "get_bottom",
    ),
    "color": _members(
        "aqua",
        "black",
        "blue",
        "fuchsia",
        "gray",
        "green",
        "grey",
        "lime",
        "maroon",
        "navy",
        "olive",
        "orange",
        "purple",
        "red",
        "silver",
        "teal",
        "white",
        "yellow",
        "rgb",
        "r",
        "g",
        "b",
        "a",
        "from_gradient",
        "new",
        "orange",
        "transparent",
    ),
    "currency": _members(
        "USD",
        "EUR",
        "GBP",
        "JPY",
        "AUD",
        "CAD",
        "CHF",
        "CNY",
        "KRW",
        "INR",
        "RUB",
        "BRL",
        "TRY",
        "ZAR",
        "NZD",
        "SGD",
        "HKD",
        "NONE",
        "USDT",
        "USDC",
        "DAI",
        "TUSD",
        "FDUSD",
        "BTC",
        "ETH",
    ),
    "display": _members(
        "all",
        "none",
        "pane",
        "data_window",
        "status_line",
        "price_scale",
        "price_scale_and_data_window",
        "regular",
        "smart",
        "plot_and_data_window",
    ),
    "format": _members(
        "price",
        "volume",
        "percent",
        "inherit",
        "number",
        "currency",
        "integer",
        "time",
        "date",
        "price_per_chart_scale",
        "mintick",
        "fraction",
        "scientific",
        "enum",
    ),
    "hline": _members(
        "new",
        "style_solid",
        "style_dashed",
        "style_dotted",
        "style_dashed_dotted",
        "style_dashed_dotted_dotted",
        "style_arrow_left",
        "style_arrow_right",
        "style_arrow_both",
    ),
    "input": _members(
        "int",
        "float",
        "bool",
        "string",
        "color",
        "source",
        "timeframe",
        "symbol",
        "price",
        "session",
        "time",
        "text_area",
        "enum",
        "integer",
        "resolution",
        "string",
    ),
    "label": _members(
        "new",
        "delete",
        "set_x",
        "set_y",
        "set_xy",
        "set_text",
        "set_color",
        "set_textcolor",
        "set_style",
        "set_size",
        "set_textalign",
        "set_tooltip",
        "set_xloc",
        "set_yloc",
        "get_x",
        "get_y",
        "get_text",
        "style_none",
        "style_label_up",
        "style_label_down",
        "style_label_left",
        "style_label_right",
        "style_label_lower_left",
        "style_label_lower_right",
        "style_label_upper_left",
        "style_label_upper_right",
        "style_circle",
        "style_flag",
        "style_arrowup",
        "style_arrowdown",
    ),
    "line": _members(
        "new",
        "delete",
        "set_x1",
        "set_y1",
        "set_x2",
        "set_y2",
        "set_xy1",
        "set_xy2",
        "set_color",
        "set_width",
        "set_style",
        "set_extend",
        "get_x1",
        "get_y1",
        "get_x2",
        "get_y2",
    ),
    "location": _members(
        "top",
        "top_left",
        "top_center",
        "top_right",
        "bottom",
        "bottom_left",
        "bottom_center",
        "bottom_right",
        "middle_left",
        "middle_center",
        "middle_right",
        "absolute",
        "belowbar",
        "abovebar",
    ),
    "map": _members(
        "new", "clear", "contains_key", "get", "put", "remove", "keys", "values", "size"
    ),
    "math": _members(
        "pi",
        "e",
        "phi",
        "abs",
        "acos",
        "asin",
        "atan",
        "avg",
        "ceil",
        "cos",
        "exp",
        "floor",
        "log",
        "log10",
        "max",
        "min",
        "pow",
        "random",
        "round",
        "round_to_mintick",
        "sign",
        "sin",
        "sqrt",
        "sum",
        "tan",
        "todegrees",
        "toradians",
    ),
    "matrix": _members(
        "new",
        "new_float",
        "new_int",
        "get",
        "set",
        "rows",
        "columns",
        "size",
        "add_row",
        "add_col",
        "remove_row",
        "remove_col",
        "clear",
        "copy",
        "fill",
        "transpose",
        "reverse",
        "sort",
        "concat",
    ),
    "plot": _members(
        "style_line",
        "style_stepline",
        "style_histogram",
        "style_cross",
        "style_area",
        "style_columns",
        "style_circles",
        "style_linebr",
        "style_areabr",
        "style_stepline_diamond",
        "style_steplinebr",
        "style_histogram_steps",
        "style_linebr",
        "style_areabr",
        "chart",
        "color",
        "linewidth",
        "style",
        "title",
        "display",
        "join",
        "hline",
        "fill",
        "colorer",
        "offset",
        "show_last",
        "format",
        "precision",
        "editable",
        "display_name",
    ),
    "position": _members(
        "top",
        "bottom",
        "center",
        "left",
        "right",
        "top_left",
        "top_right",
        "bottom_left",
        "bottom_right",
        "absolute",
        "none",
    ),
    "order": _members("ascending", "descending"),
    "request": _members(
        "security",
        "security_lower_tf",
        "security_syminfo",
        "financial",
        "financial_result",
        "dividends",
        "earnings",
        "quandl",
        "seed",
        "economic",
        "currency_rate",
    ),
    "shape": _members(
        "circle",
        "square",
        "triangleup",
        "triangledown",
        "diamond",
        "flag",
        "arrowup",
        "arrowdown",
        "cross",
        "xcross",
        "labeldown",
        "labelup",
        "none",
    ),
    "size": _members("auto", "tiny", "small", "normal", "large", "huge"),
    "strategy": _members(
        "long",
        "short",
        "flat",
        "percent_of_equity",
        "cash",
        "fixed",
        "contracts",
        "direction",
        "entries",
        "exits",
        "entry",
        "exit",
        "close",
        "close_all",
        "cancel",
        "cancel_all",
        "order",
        "position_size",
        "position_avg_price",
        "initial_capital",
        "closedtrades",
        "closedtrades_profit",
        "closedtrades_loss",
        "closedtrades_wintrades",
        "closedtrades_losstrades",
        "wintrades",
        "losstrades",
        "grossprofit",
        "grossloss",
        "netprofit",
        "netprofit_percent",
        "openprofit",
        "openprofit_percent",
        "equity",
        "max_drawdown",
        "max_drawdown_percent",
        "max_runup",
        "max_runup_percent",
        "risk",
        "position_avg_price",
        "default_qty_type",
        "default_qty_value",
        "pyramiding",
        "margin_long",
        "margin_short",
        "commission_type",
        "commission_value",
        "slippage",
        "use_bar_magnifier",
        "calc_on_order_fills",
        "calc_on_every_tick",
        "process_orders_on_close",
        "close_entries_rule",
        "max_bars_back",
        "min_ticksize",
        "is_last_bar",
        "is_first_bar",
        "is_connected",
        "is_realtime",
        "commission",
        "opentrades",
        "closedtrades",
        "closedtrades_profit",
        "closedtrades_loss",
        "closedtrades_entry_price",
        "closedtrades_exit_price",
        "closedtrades_entry_time",
        "closedtrades_exit_time",
        "closedtrades_entry_bar_index",
        "closedtrades_exit_bar_index",
        "opentrades_entry_price",
        "opentrades_exit_price",
        "opentrades_entry_time",
        "opentrades_exit_time",
        "opentrades_entry_bar_index",
        "opentrades_exit_bar_index",
        "risk",
        "allow_entry_in",
        "oca",
        "account_currency",
        "eventrades",
        "default_entry_qty",
        "position_entry_name",
        "convert_to_symbol",
        "direction",
        "max_drawdown",
        "max_drawdown_percent",
        "max_intraday_loss",
        "max_intraday_loss_percent",
        "max_position_size",
        "max_position_size_percent",
    ),
    "syminfo": _members(
        "tickerid",
        "ticker",
        "prefix",
        "currency",
        "basecurrency",
        "description",
        "type",
        "root",
        "mintick",
        "pointvalue",
        "session",
        "timezone",
        "volumetype",
        "industry",
        "sector",
        "employees",
        "shares_outstanding_float",
        "shares_outstanding_total",
        "target_price_average",
        "recommendations_buy",
        "recommendations_sell",
    ),
    "table": _members(
        "new",
        "cell",
        "cell_set_text",
        "cell_set_bgcolor",
        "cell_set_text_color",
        "cell_set_text_size",
        "cell_set_tooltip",
        "cell_set_text_halign",
        "cell_set_text_valign",
        "cell_set_width",
        "cell_set_height",
        "cell_set_border_color",
        "cell_set_border_width",
        "delete",
        "clear",
        "set_position",
        "merge_cells",
    ),
    "ta": _members(
        "crossover",
        "crossunder",
        "sma",
        "ema",
        "rma",
        "wma",
        "hma",
        "vwma",
        "dema",
        "tema",
        "trima",
        "frama",
        "swma",
        "cum",
        "obv",
        "bb",
        "alma",
        "linreg",
        "rsi",
        "atr",
        "tr",
        "cci",
        "cmo",
        "mfi",
        "wpr",
        "macd",
        "stoch",
        "bbands",
        "kc",
        "donchian",
        "supertrend",
        "sar",
        "adx",
        "dmi",
        "plusdi",
        "minusdi",
        "aroon",
        "highest",
        "lowest",
        "highestbars",
        "lowestbars",
        "barssince",
        "valuewhen",
        "change",
        "roc",
        "momentum",
        "tsi",
        "correlation",
        "percentrank",
        "percentile_linear_interpolation",
        "percentile_nearest_rank",
        "variance",
        "dev",
        "stdev",
        "median",
        "mode",
        "range",
        "midpoint",
        "midprice",
        "wpr",
        "vwap",
        "anchored_vwap",
        "pivothigh",
        "pivotlow",
        "pivot",
        "cog",
        "correlation",
    ),
    "alert": _members(
        "alert",
        "frequency",
        "freq_all",
        "freq_once_per_bar",
        "freq_once_per_bar_close",
        "freq_daily",
        "freq_weekly",
        "freq_monthly",
        "freq_once_per_minute",
        "freq_once_per_hour",
    ),
    "runtime": _members("error", "warning", "na", "is_profiling", "profiler"),
    "str": _members(
        "tostring",
        "tonumber",
        "length",
        "upper",
        "lower",
        "contains",
        "replace",
        "split",
        "format",
        "format_time",
    ),
    "ticker": _members(
        "new", "modify", "standard", "heikinashi", "renko", "linebreak", "kagi", "pointfigure"
    ),
    "dayofweek": _members(
        "sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"
    ),
    "extend": _members("none", "left", "right", "both"),
    "xloc": _members("bar_index", "bar_time"),
    "yloc": _members("price", "abovebar", "belowbar"),
    "text": _members(
        "align_left",
        "align_center",
        "align_right",
        "size_auto",
        "size_small",
        "size_normal",
        "size_large",
        "size_huge",
    ),
    "chart": _members("bg", "fg", "left", "right", "top", "bottom", "center"),
    "timeframe": _members(
        "period",
        "multiplier",
        "isdaily",
        "isweekly",
        "ismonthly",
        "isintraday",
        "isminutes",
        "isseconds",
        "isdwm",
        "issec",
        "in_seconds",
        "change",
        "from_seconds",
        "chart",
    ),
    "barstate": _members(
        "isconfirmed", "isfirst", "islast", "ishistory", "isrealtime", "islastconfirmedhistory"
    ),
    "session": _members(
        "regular",
        "extended",
        "premarket",
        "postmarket",
        "isfirstbar",
        "islastbar",
        "ispremarket",
        "ispostmarket",
    ),
}

# Values that are not order/position state.  The runtime fills in dynamic
# values (such as timeframe.period) from the current report context.
_CONSTANT_VALUES: dict[tuple[str, str], Any] = {
    ("math", "pi"): 3.141592653589793,
    ("math", "e"): 2.718281828459045,
    ("math", "phi"): 1.618033988749895,
    ("syminfo", "tickerid"): "UNKNOWN",
    ("syminfo", "ticker"): "UNKNOWN",
    ("syminfo", "prefix"): "",
    ("syminfo", "currency"): "USD",
    ("syminfo", "basecurrency"): "",
    ("syminfo", "description"): "synthetic",
    ("syminfo", "type"): "crypto",
    ("syminfo", "root"): "",
    ("syminfo", "mintick"): 0.01,
    ("syminfo", "pointvalue"): 1.0,
    ("syminfo", "timezone"): "Etc/UTC",
    ("syminfo", "volumetype"): "base",
}

NAMESPACE_MEMBERS = MappingProxyType(_NAMESPACE_MEMBERS)


def is_known_namespace(namespace: str) -> bool:
    return namespace in _NAMESPACE_MEMBERS


def is_known_member(namespace: str, member: str) -> bool:
    return member in _NAMESPACE_MEMBERS.get(namespace, ())


def constant_value(namespace: str, member: str) -> Any:
    return _CONSTANT_VALUES.get((namespace, member))
